Update README to use more recent versions
The default version is now `0.17` instead of `0.15`.

The `debian` box installs golang 1.3 via `apt_get`, which fails to install the lib crypto (`../gopath/src/golang.org/x/crypto/ed25519/ed25519.go:54: undefined: crypto.SignerOpts` - this was added on golang 1.4). Using the latest version of golang is probably a better example to use with `HEAD` version.